"""Database creation

Revision ID: 031a474b6798
Revises: 4b03c715322e
Create Date: 2024-11-23 16:28:40.832544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031a474b6798'
down_revision = '4b03c715322e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
