"""Database creation

Revision ID: 1b92ced274fd
Revises: 631c403bac47
Create Date: 2024-11-23 16:20:59.065035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b92ced274fd'
down_revision = '631c403bac47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
