"""Database creation

Revision ID: 4b03c715322e
Revises: 64c9c71f9e4b
Create Date: 2024-11-23 16:26:09.404527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b03c715322e'
down_revision = '64c9c71f9e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
