"""Database creation

Revision ID: 64c9c71f9e4b
Revises: 1b92ced274fd
Create Date: 2024-11-23 16:23:54.447968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64c9c71f9e4b'
down_revision = '1b92ced274fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('comments', sa.String(), nullable=True))
    op.drop_column('user', 'theme_rules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('theme_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user', 'comments')
    # ### end Alembic commands ###
